[versions]
agp = "8.13.1"
kotlin = "2.0.21"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
hilt = "2.57.2"
kotlinxSerialization = "1.4.1"
kotlinxCoroutines = "1.10.2"
media3Session = "1.8.0"
ksp = "2.0.21-1.0.28"
room = "2.6.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "media3Session" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat" }
material = { group = "com.google.android.material", name = "material" }
material3 = { group = "com.google.android.material3", name = "material3" }
hilt-android = { group= "com.google.dagger", name = "hilt-android",  version.ref = "hilt" }
hilt-compiler = { group= "com.google.dagger", name = "hilt-compiler",  version.ref = "hilt" }
kotlinSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesGuave = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "kotlinxCoroutines" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hiltGradlePlugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
